variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: "Release"


trigger: 
  - master
pr:
- master
jobs:
  - job: "BuildWindows"
    displayName: "Building .NET Application"
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: DotNetCoreInstaller@1
        displayName: "Use .NET Core sdk 2.2.100"
        inputs:
          version: 2.2.100
      - task: DotNetCoreCLI@2
        inputs:
          command: build
      - task: DotNetCoreCLI@2
        inputs:
          command: pack
      - task: PublishPipelineArtifact@1
        displayName: "Publish Artifact"
        inputs:
          targetPath: "$(build.artifactstagingdirectory)"
          ArtifactName: "build"
  - job: "BuildLinux"
    displayName: "Building .NET Application"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: DotNetCoreInstaller@1
        displayName: "Use .NET Core sdk 2.2.100"
        inputs:
          version: 2.2.100
      - task: DotNetCoreCLI@2
        inputs:
          command: build
      - task: DotNetCoreCLI@2
        inputs:
          command: build

