variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: "Release"


trigger: 
  - master
pr:
- master
jobs:
  - job: "Build"
    displayName: "Building .NET Application"
    strategy:
      matrix: 
        Windows:
          imageToUse: 'windows-2019'
        Linux:
          imageToUse: 'ubuntu-latest'
    pool:
      vmImage: imageToUse
    steps:
      - task: DotNetCoreInstaller@0
        displayName: "Use .NET Core sdk 2.2.100"
        inputs:
          version: 2.2.100

      - script: dotnet publish --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
        displayName: "dotnet publish"

      - task: PublishPipelineArtifact@0
        displayName: "Publish Artifact"
        inputs:
          targetPath: "$(build.artifactstagingdirectory)"
          ArtifactName: "build"
